//! Robustness properties of the lexer.
//!
//! These are the properties every later stage depends on, and the ones a
//! language that agents are supposed to manipulate safely cannot afford to
//! break:
//!
//! 1. lexing **never panics**, whatever the input;
//! 2. it **always terminates**, including on pathological nesting;
//! 3. token spans stay inside the source and land on character boundaries;
//! 4. tokens are ordered and do not overlap;
//! 5. diagnostics point inside the source;
//! 6. the result is deterministic.
//!
//! The inputs are generated by a fixed-seed pseudo-random walk over an
//! alphabet of characters that are interesting to a lexer. No third-party
//! fuzzing dependency is needed, and a failure always reproduces from the
//! printed seed. `fuzz/README.md` records how to run a real libFuzzer campaign
//! once one is warranted.

use nudo_lexer::{Token, TokenKind, tokenize};
use nudo_source::SourceMap;

/// The characters the generator draws from: every token start, every
/// terminator, and a few characters the lexer must reject.
const ALPHABET: &[char] = &[
    'f', 'n', 'l', 'e', 't', 'x', 'A', '_', '0', '1', '9', ' ', '\t', '\n', '\r', '(', ')', '{',
    '}', ':', ',', '-', '>', '=', '+', '*', '/', ';', '"', '\\', '.', '@', '#', '€', 'é',
    '\u{feff}',
];

/// xorshift64* — small, deterministic and dependency-free.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Rng(seed | 1)
    }

    fn next_u64(&mut self) -> u64 {
        let mut state = self.0;
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        self.0 = state;
        state.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    fn below(&mut self, bound: usize) -> usize {
        (self.next_u64() % bound as u64) as usize
    }
}

fn random_source(rng: &mut Rng, length: usize) -> String {
    let mut source = String::with_capacity(length);
    for _ in 0..length {
        source.push(ALPHABET[rng.below(ALPHABET.len())]);
    }
    source
}

fn lex(text: &str) -> (SourceMap, Vec<Token>, nudo_diagnostics::Diagnostics) {
    let mut sources = SourceMap::new();
    let id = sources.add("robustness.nudo", text);
    let file = sources.get(id).expect("just added");
    let lexed = tokenize(file);
    let (tokens, diagnostics) = lexed.into_parts();
    (sources, tokens, diagnostics)
}

fn assert_invariants(text: &str, seed: u64) {
    let (_sources, tokens, diagnostics) = lex(text);

    assert_eq!(
        tokens.iter().filter(|token| token.is_eof()).count(),
        1,
        "seed {seed}: exactly one Eof token is required for {text:?}"
    );
    assert!(
        tokens.last().is_some_and(|token| token.is_eof()),
        "seed {seed}: Eof must be the last token for {text:?}"
    );

    let mut previous_end = 0;
    for token in &tokens {
        let span = token.span();
        let (start, end) = (span.start().as_usize(), span.end().as_usize());
        assert!(
            end <= text.len(),
            "seed {seed}: span {span} escapes the source for {text:?}"
        );
        assert!(
            path_starts_at_char_boundary(text, start) && text.is_char_boundary(end),
            "seed {seed}: span {span} is not on character boundaries for {text:?}"
        );
        if token.kind() != TokenKind::Eof {
            assert!(
                start >= previous_end,
                "seed {seed}: tokens overlap or run backwards for {text:?}"
            );
        }
        previous_end = end;
    }

    for diagnostic in &diagnostics {
        let Some(span) = diagnostic.span() else {
            continue;
        };
        assert!(
            span.end().as_usize() <= text.len(),
            "seed {seed}: diagnostic span {span} escapes the source for {text:?}"
        );
        assert!(
            text.is_char_boundary(span.start().as_usize()),
            "seed {seed}: diagnostic span {span} is not on a boundary for {text:?}"
        );
    }
}

fn path_starts_at_char_boundary(text: &str, offset: usize) -> bool {
    text.is_char_boundary(offset)
}

#[test]
fn random_inputs_hold_every_invariant() {
    let mut rng = Rng::new(0x9E37_79B9_7F4A_7C15);
    for case in 0..2_000 {
        let length = rng.below(160);
        let source = random_source(&mut rng, length);
        assert_invariants(&source, case);
    }
}

#[test]
fn structured_random_inputs_hold_every_invariant() {
    // Longer inputs with more structure: the generator is biased towards
    // characters that open a region (comment, text literal, number).
    let mut rng = Rng::new(0xD1CE_1234_5678_9ABC);
    for case in 0..300 {
        let mut source = String::new();
        for _ in 0..rng.below(40) + 1 {
            match rng.below(6) {
                0 => source.push_str("/*"),
                1 => source.push_str("*/"),
                2 => source.push('"'),
                3 => source.push_str("//"),
                4 => source.push_str("1_"),
                _ => {
                    let length = rng.below(12) + 1;
                    let chunk = random_source(&mut rng, length);
                    source.push_str(&chunk);
                }
            }
        }
        assert_invariants(&source, 10_000 + case);
    }
}

#[test]
fn lexing_is_deterministic() {
    let mut rng = Rng::new(0x0BAD_C0DE_DEAD_BEEF);
    for _ in 0..200 {
        let length = rng.below(200) + 1;
        let source = random_source(&mut rng, length);
        let (_, first_tokens, first_diagnostics) = lex(&source);
        let (_, second_tokens, second_diagnostics) = lex(&source);
        assert_eq!(first_tokens, second_tokens, "tokens differ for {source:?}");
        assert_eq!(
            first_diagnostics.len(),
            second_diagnostics.len(),
            "diagnostics differ for {source:?}"
        );
    }
}

#[test]
fn deeply_nested_block_comments_terminate() {
    let depth = 1_000;
    let mut source = "/*".repeat(depth);
    source.push_str(" let buried = 1; ");
    source.push_str(&"*/".repeat(depth));
    source.push_str("let visible = 2;");

    let (_, tokens, diagnostics) = lex(&source);
    assert!(diagnostics.is_empty(), "a balanced nest is not an error");
    assert_eq!(
        tokens.iter().map(|token| token.kind()).collect::<Vec<_>>(),
        vec![
            TokenKind::KeywordLet,
            TokenKind::Ident,
            TokenKind::Equals,
            TokenKind::IntLiteral,
            TokenKind::Semi,
            TokenKind::Eof,
        ]
    );
}

#[test]
fn unbalanced_nesting_is_reported_once() {
    let source = "/*".repeat(50);
    let (_, tokens, diagnostics) = lex(&source);
    assert_eq!(diagnostics.error_count(), 1);
    assert_eq!(tokens.len(), 1, "only Eof remains");
}

#[test]
fn pathological_inputs_stay_bounded() {
    assert_invariants("", 1);
    assert_invariants(&"\"".repeat(1_000), 2);
    assert_invariants(&"1_".repeat(1_000), 3);
    assert_invariants(&"-".repeat(1_000), 4);
    assert_invariants(&"\u{feff}".repeat(10), 5);
    assert_invariants(&"a".repeat(10_000), 6);
}
