[package]
name = "nudo-ast"
description = "Abstract syntax tree and AST visitors."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
nudo-span.workspace = true
nudo-syntax.workspace = true

[dev-dependencies]
nudo-parser.workspace = true
nudo-source.workspace = true

[lints]
workspace = true
