[package]
name = "nudo-schema"
description = "Schema types for the nudo.toml manifest and nudo.lock lockfile."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true
